// MUN 文件生成与渲染逻辑
import { PREAMBULATORY_PHRASES, OPERATIVE_PHRASES } from '../data/munData'
import {
  DURATIONS, TONES, type SpeechDuration, type SpeechTone, type PointSuggestion,
} from './recommend'

export interface PPInput {
  committee: string
  conference: string
  country: string
  delegate: string
  school: string
  topic: string
  bgData: string
  pastActions: string
  countryPolicy: string
  officialQuote: string
  solutions: string[]
}

export function genPositionPaper(i: PPInput): string {
  const sol = i.solutions.filter(Boolean)
  const solText = sol.length
    ? sol.map((s, k) => `(${k + 1}) ${ensureEnd(s, '.')}`).join(' ')
    : '(1) [add a concrete proposal with who/what/how].'
  return `Committee: ${i.committee || '[Committee]'}${i.conference ? `\nConference: ${i.conference}` : ''}
Country:   ${i.country || '[Country]'}
Delegate:  ${i.delegate || '[Delegate Name]'}${i.school ? `, ${i.school}` : ''}
Topic:     ${i.topic || '[Topic]'}

${i.bgData ? i.bgData.trim() : '[Background: state the current situation with a credible statistic and its source.]'} ${i.pastActions ? ' ' + i.pastActions.trim() : ' Recalling relevant United Nations resolutions and the Charter of the United Nations, the international community has taken steps to address this matter; however, significant gaps remain.'}

${i.country ? i.country : '[Country]'} has consistently attached great importance to this issue. ${i.countryPolicy ? i.countryPolicy.trim() + ' ' : ''}${i.officialQuote ? `As stated by the government of ${i.country || '[Country]'}, "${i.officialQuote.trim()}" ` : ''}My delegation believes that a durable solution must respect international law, national sovereignty, and the principles of the United Nations Charter, while addressing the root causes rather than the symptoms alone.

To that end, ${i.country || '[Country]'} proposes the following measures: ${solText} ${i.country || '[Country]'} stands ready to work constructively with all delegations to build consensus and translate these proposals into concrete action.

---
AI-generated draft · 请核实全部事实、数据与引用后再提交 · Generated by MUN Compass`
}

export interface SpeechInput {
  type: 'gsl' | 'caucus'
  country: string
  topic: string
  position: string
  points: { claim: string; evidence: string }[]
  callToAction: string
  subtopic?: string
}

export function genSpeech(i: SpeechInput): string {
  const c = i.country || '[Country]'
  const pts = i.points.filter((p) => p.claim.trim())
  if (i.type === 'caucus') {
    const p = pts[0]
    return `Thank you, Honorable Chair.
On the issue of ${i.subtopic || i.topic || '[sub-topic]'}, ${c} ${i.position ? i.position.trim() + '. ' : 'believes that urgent, coordinated action is required.'}${p ? ` ${ensureEnd(p.claim, ',')} as shown by ${p.evidence || '[evidence]'}. ` : ''}${i.callToAction ? ensureEnd(i.callToAction, '.') : `My delegation calls upon all parties to take concrete steps without delay.`}
I yield my time to the Chair.
---
AI-generated draft · MUN Compass · ${wordCountHint('caucus')}`
  }
  const body = pts.length
    ? pts
        .map((p, k) => {
          const ord = ['First', 'Second', 'Third'][k] || `${k + 1}th`
          return `${ord}, ${lower0(p.claim.trim())} ${p.evidence ? `According to ${p.evidence.trim()}, this trend demands our immediate attention. ` : ''}`
        })
        .join('')
    : 'First, [state problem with evidence]. Second, [state argument with data]. Third, [state proposed action]. '
  return `Honorable Chair, distinguished delegates,
${c} ${i.position ? i.position.trim() + '. ' : 'believes that the international community must act with unity and purpose.'}${body}${i.callToAction ? 'My delegation calls upon this committee to ' + lower0(i.callToAction.trim()) + (i.callToAction.trim().endsWith('.') ? ' ' : '. ') : 'My delegation calls upon this committee to support concrete, cooperative solutions. '}
Thank you. I yield my time to the Chair.
---
AI-generated draft · MUN Compass · ${wordCountHint('gsl')}`
}

function wordCountHint(t: string) {
  return t === 'gsl' ? '目标 130-200 词 / 60-90 秒' : '目标 60-120 词 / 30-60 秒'
}

export function countWords(s: string) {
  return s.trim() ? s.trim().split(/\s+/).length : 0
}

// ============ Draft Resolution ============
export interface ResClause {
  id: string
  phrase: string
  text: string
  children: ResClause[]
}
export interface ResDoc {
  body: string // 机构开场名
  committee: string
  conference: string
  sponsors: string
  signatories: string
  topic: string
  preamb: ResClause[]
  oper: ResClause[]
}

export const newClause = (phrase: string): ResClause => ({
  id: Math.random().toString(36).slice(2, 10),
  phrase,
  text: '',
  children: [],
})

const PP_INDENT = '      '
const OP_LETTER = (n: number) => `${String.fromCharCode(97 + n)})`
const OP_ROMAN = (n: number) => `${['i','ii','iii','iv','v','vi','vii','viii'][n] || n + 1})`

function renderOperText(clause: ResClause, level: 0 | 1 | 2, index: number, last: boolean): string {
  const prefix = level === 0 ? `${index + 1}. ` : level === 1 ? OP_LETTER(index) + ' ' : OP_ROMAN(index) + ' '
  const indent = level === 0 ? '    ' : level === 1 ? '        ' : '            '
  const isLastTop = level === 0 && last
  const hasKids = clause.children.length > 0
  const tail = level === 0 ? (isLastTop ? (hasKids ? '' : ';') : (hasKids ? '' : ';')) : level === 1 ? (hasKids ? '' : ';') : ';'
  // 顶层最后一条（含子条款链）以句号结束由末端控制
  let line = `${indent}${prefix}${clause.phrase} ${clause.text || '[...]'}${tail}\n`
  if (hasKids) {
    clause.children.forEach((ch, k) => {
      line += renderOperText(ch, (level + 1) as 1 | 2, k, k === clause.children.length - 1)
    })
  }
  return line
}

export function renderResolutionText(d: ResDoc): string {
  let out = `Committee:   ${d.committee}\n${d.conference ? `Conference: ${d.conference}\n` : ''}Sponsors:    ${d.sponsors}\nSignatories: ${d.signatories}\nTopic:       ${d.topic}\n\n${d.body},\n`
  d.preamb.forEach((p) => {
    out += `${PP_INDENT}${p.phrase} ${p.text || '[...]'},\n`
  })
  if (d.preamb.length && d.oper.length) out += '\n'
  let operText = ''
  d.oper.forEach((o, k) => {
    operText += renderOperText(o, 0, k, k === d.oper.length - 1)
  })
  // 末字符分号改句号
  operText = operText.trimEnd().replace(/;$/, '.')
  out += operText
  out += `\n\n---\nAI-generated draft · MUN Compass · 依据 UNA-USA 格式（PP 斜体 / OP 下划线）`
  return out
}

// 校验问题
export function lintResolution(d: ResDoc): string[] {
  const errs: string[] = []
  if (!d.sponsors.trim()) errs.push('缺少 Sponsors（起草国）')
  if (!d.topic.trim()) errs.push('缺少议题')
  if (!d.oper.length) errs.push('至少需要 1 条 Operative Clause')
  d.preamb.forEach((p, k) => {
    if (!PREAMBULATORY_PHRASES.includes(p.phrase)) errs.push(`PP#${k + 1} 开头词不在标准词库`)
  })
  d.oper.forEach((o, k) => {
    if (!OPERATIVE_PHRASES.includes(o.phrase)) errs.push(`OP#${k + 1} 开头词不在标准词库`)
  })
  const all = [...d.preamb, ...flatOper(d.oper)]
  all.forEach((c) => {
    if (!c.text.trim()) errs.push(`「${c.phrase}」内容为空`)
  })
  return errs
}

function flatOper(cs: ResClause[]): ResClause[] {
  return cs.flatMap((c) => [c, ...flatOper(c.children)])
}

// ============ utils ============
function ensureEnd(s: string, ch: string) {
  const t = s.trim()
  return t + (/[.,;:]$/.test(t) ? '' : ch)
}
function lower0(s: string) {
  return s ? s[0].toLowerCase() + s.slice(1) : s
}

// ============ 讲稿 V2（会议信息 + 时长 + 语气 + 推荐论点） ============
export interface SpeechV2Input {
  committee: string
  country: string
  topic: string
  occasion: string
  duration: SpeechDuration
  tone: SpeechTone
  subtopic: string
  position: string
  points: PointSuggestion[]
  callToAction: string
}

const ORDINAL = ['First', 'Second', 'Third', 'Fourth', 'Fifth', 'Sixth', 'Seventh']

export function genSpeechV2(i: SpeechV2Input): string {
  const dur = DURATIONS.find((d) => d.id === i.duration)!
  const tone = TONES.find((t) => t.id === i.tone)!
  const c = i.country || '[Country]'
  const subject = i.occasion.includes('Caucus') && i.subtopic ? i.subtopic : i.topic || '[topic]'

  const pts = i.points.slice(0, dur.maxPoints).filter((p) => p.claim.trim())
  const detail: 'short' | 'medium' | 'long' = i.duration <= 2 ? 'short' : i.duration === 5 ? 'medium' : 'long'

  let out = 'Honorable Chair, distinguished delegates,\n\n'
  out += tone.openers[0] + '\n\n'

  const pos = i.position ? ensureEnd(i.position, '.') : `[State ${c}'s core position in one sentence.]`
  out += `${c} ${tone.verbs[0]} that ${lower0(pos)} `
  out += `On the issue of ${subject}, I would like to make ${pts.length} point${pts.length === 1 ? '' : 's'}.\n\n`

  pts.forEach((p, k) => {
    const claim = p.claim.trim()
    out += `${ORDINAL[k] || `${k + 1}th`}, ${claim.charAt(0).toUpperCase() + claim.slice(1)}. `
    out += `According to ${p.evidence || '[a credible source]'}, this is a documented reality rather than an abstract concern.\n`
    if (detail === 'medium') {
      out += `Let me be specific: [insert one statistic or country-level example for ${c}]. `
      out += `For my country, this matters because [explain the direct national interest].\n`
    } else if (detail === 'long') {
      out += `Consider the evidence in detail: [provide a statistic with its source and year]. `
      out += `In the case of [country or case example], we have seen that [describe the lesson]. `
      out += `My delegation ${tone.verbs[k % tone.verbs.length]} this approach because [connect it to the Charter or a relevant resolution].\n`
    }
    out += '\n'
  })

  out += i.callToAction
    ? `My delegation therefore calls upon this committee to ${lower0(i.callToAction.trim())}. `
    : 'My delegation calls upon this committee to act on the proposals set out above. '
  out += tone.closers[0] + '\n\n'
  out += 'Thank you. I yield my time to the Chair.\n'
  out += `\n---\nAI-generated draft · MUN Compass · 目标 ${dur.words[0]}-${dur.words[1]} 词 / ${tone.label}语气 · 请将括号内提示替换为真实数据与案例后使用`
  return out
}
